### ISSUE TITLE
Type error after deploying function on Lmabda

### ISSUE THREAD

**Issue by dev3100** [psquickitjayant/cloudwatch2loggly#7]
Hi there, I'm not really great at node and need some assistance with below error I receive everytime lambda is invoked:

2018-09-21T16:40:35.755Z	b08fb74a-bdbc-11e8-a555-e93a97580243	TypeError: Cannot read property 'data' of undefined
at exports.handler (/var/task/index.js:45:44)

Code base works fine for individual log triggers but doesn't work with cloudwatch events feed.

**Comment by varshneyjayant** [comment]
Your event.awslogs is undefined. This is a very old code. Please check the latest AWS Node JS documentation.

**Comment by dev3100** [comment]
@varshneyjayant well, you were very eager to close the issue without resolution or of any help. I tried the latest AWS Node JS code and throws the same error when I setup the cloudwatch event as an input. Maybe I'm asking to wrong people for the help.

**Comment by varshneyjayant** [comment]
Haha .. sorry for that. I am no longer active on this project. Could you please contact @loggly directly? :)

**Comment by dev3100** [comment]
@varshneyjayant sure thing..sorry for outburst. I'll try to contribute the update.
